### ISSUE TITLE
Building a SIAPP issue

### ISSUE THREAD

**Issue by Mr-Swan-Siemens** [siemens/siapp-sdk#14]
[siapp-sdk-master.zip](https://github.com/user-attachments/files/18024808/siapp-sdk-master.zip)
Hello dear support!
Please help me to fix the issue of building SIAPP.
I followed your manual to generate the DemoProject and in both variants I had no luck to get good result.

**1. The first command - python build.py DemoProject - the result is below**

 PS D:\SAS\SIAPP\siapp-sdk-master\siapp-sdk-master> python build.py DemoProject
Traceback (most recent call last):
  File "D:\SAS\SIAPP\siapp-sdk-master\siapp-sdk-master\build.py", line 276, in <module>
    init_multiarch_qemu()
    ~~~~~~~~~~~~~~~~~~~^^
  File "D:\SAS\SIAPP\siapp-sdk-master\siapp-sdk-master\helper.py", line 101, in init_multiarch_qemu
    run_subprocess([BuildArgs.tool, 'run', '--rm', '--privileged',
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                    'multiarch/qemu-user-static', '--reset', '-p', 'yes'])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SAS\SIAPP\siapp-sdk-master\siapp-sdk-master\helper.py", line 33, in run_subprocess
    result = subprocess.run(
        command_list,
        capture_output=True,
        text=True)
  File "C:\Users\z0043pnp\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 554, in run
    with Popen(*popenargs, **kwargs) as process:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\z0043pnp\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 1036, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass_fds, cwd, env,
                        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                        gid, gids, uid, umask,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        start_new_session, process_group)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\z0043pnp\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 1548, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
                             # no special security
                             ^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
                             cwd,
                             ^^^^
                             startupinfo)
                             ^^^^^^^^^^^^

**2. The second command - python build.py -t docker DemoProject - the result is below**

Setting /usr/bin/qemu-alpha-static as binfmt interpreter for alpha
Setting /usr/bin/qemu-arm-static as binfmt interpreter for arm
Setting /usr/bin/qemu-armeb-static as binfmt interpreter for armeb
Setting /usr/bin/qemu-sparc-static as binfmt interpreter for sparc
Setting /usr/bin/qemu-sparc32plus-static as binfmt interpreter for sparc32plus
Setting /usr/bin/qemu-sparc64-static as binfmt interpreter for sparc64
Setting /usr/bin/qemu-ppc-static as binfmt interpreter for ppc
Setting /usr/bin/qemu-ppc64-static as binfmt interpreter for ppc64
Setting /usr/bin/qemu-ppc64le-static as binfmt interpreter for ppc64le
Setting /usr/bin/qemu-m68k-static as binfmt interpreter for m68k
Setting /usr/bin/qemu-mips-static as binfmt interpreter for mips
Setting /usr/bin/qemu-mipsel-static as binfmt interpreter for mipsel
Setting /usr/bin/qemu-mipsn32-static as binfmt interpreter for mipsn32
Setting /usr/bin/qemu-mipsn32el-static as binfmt interpreter for mipsn32el
Setting /usr/bin/qemu-mips64-static as binfmt interpreter for mips64
Setting /usr/bin/qemu-mips64el-static as binfmt interpreter for mips64el
Setting /usr/bin/qemu-sh4-static as binfmt interpreter for sh4
Setting /usr/bin/qemu-sh4eb-static as binfmt interpreter for sh4eb
Setting /usr/bin/qemu-s390x-static as binfmt interpreter for s390x
Setting /usr/bin/qemu-aarch64-static as binfmt interpreter for aarch64
Setting /usr/bin/qemu-aarch64_be-static as binfmt interpreter for aarch64_be
Setting /usr/bin/qemu-hppa-static as binfmt interpreter for hppa
Setting /usr/bin/qemu-riscv32-static as binfmt interpreter for riscv32
Setting /usr/bin/qemu-riscv64-static as binfmt interpreter for riscv64
Setting /usr/bin/qemu-xtensa-static as binfmt interpreter for xtensa
Setting /usr/bin/qemu-xtensaeb-static as binfmt interpreter for xtensaeb
Setting /usr/bin/qemu-microblaze-static as binfmt interpreter for microblaze
Setting /usr/bin/qemu-microblazeel-static as binfmt interpreter for microblazeel
Setting /usr/bin/qemu-or1k-static as binfmt interpreter for or1k
Setting /usr/bin/qemu-hexagon-static as binfmt interpreter for hexagon



Error response from daemon: No such container: demoproject-a8000


#0 building with "desktop-linux" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 490B done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/library/alpine:latest
#2 ...

#3 [auth] library/alpine:pull token for registry-1.docker.io
#3 DONE 0.0s

#2 [internal] load metadata for docker.io/library/alpine:latest
#2 DONE 1.6s

#4 [internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [1/8] FROM docker.io/library/alpine:latest@sha256:1e42bbe2508154c9126d48c2b8a75420c3544343bf86fd041fb7527e017a4b4a
#5 resolve docker.io/library/alpine:latest@sha256:1e42bbe2508154c9126d48c2b8a75420c3544343bf86fd041fb7527e017a4b4a 0.0s done
#5 CACHED

#6 [internal] load build context
#6 transferring context: 454.22kB 0.1s done
#6 DONE 0.1s

#7 [2/8] RUN apk add --no-cache g++ lighttpd fcgi-dev fcgi++
#7 0.326 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/armv7/APKINDEX.tar.gz
#7 0.732 34EF7F3F:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:2091:
#7 0.741 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/main: Permission denied
#7 0.741 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/armv7/APKINDEX.tar.gz
#7 0.986 34EF7F3F:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:2091:
#7 0.992 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/community: Permission denied
#7 0.996 ERROR: unable to select packages:
#7 0.997   fcgi++ (no such package):
#7 0.997     required by: world[fcgi++]
#7 0.999   fcgi-dev (no such package):
#7 0.999     required by: world[fcgi-dev]
#7 0.999   g++ (no such package):
#7 0.999     required by: world[g++]
#7 0.999   lighttpd (no such package):
#7 0.999     required by: world[lighttpd]
#7 ERROR: process "/bin/sh -c apk add --no-cache g++ lighttpd fcgi-dev fcgi++" did not complete successfully: exit code: 4
------
 > [2/8] RUN apk add --no-cache g++ lighttpd fcgi-dev fcgi++:
0.992 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/community: Permission denied
0.996 ERROR: unable to select packages:
0.997   fcgi++ (no such package):
0.997     required by: world[fcgi++]
0.999   fcgi-dev (no such package):
0.999     required by: world[fcgi-dev]
0.999   g++ (no such package):
0.999     required by: world[g++]
0.999   lighttpd (no such package):
0.999     required by: world[lighttpd]
------
Dockerfile:6
--------------------
   4 |     EXPOSE 80
   5 |
   6 | >>> RUN apk add --no-cache g++ lighttpd fcgi-dev fcgi++
   7 |
   8 |     COPY src /src
--------------------
ERROR: failed to solve: process "/bin/sh -c apk add --no-cache g++ lighttpd fcgi-dev fcgi++" did not complete successfully: exit code: 4

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/zk26aglze8r57qo3qnetwd8zk

ERROR: Could not build docker image!

**Comment by lukas-wimmer** [comment]
Hi Mr Swan,

please use the latest siapp-sdk.

**1. The first command - python build.py DemoProject - the result is below**
have you installed podman desktop?
which version is in use?
Try in a console:  "podman run hello-world" to check if podman is set up correctly

**2. The second command - python build.py -t docker DemoProject - the result is below**
seems like you are not logged on docker
Is docker working in general?
Also try in a console:  "docker run hello-world" to check if docker is set up correctly

**Comment by Mr-Swan-Siemens** [comment]
Hello Lukas-Wimmer,
I used the siapp-sdk from the link https://github.com/siemens/siapp-sdk, I don't have other option. 
The Docker seems to be running. 
PS D:\SAS\SIAPP\siapp-sdk-master\siapp-sdk-master> docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

**Comment by lukas-wimmer** [comment]
Ok seems like your are going to work with DOCKER Desktop and not with PODMAN Desktop.

Back to your problem:
Are you running your docker desktop behind a proxy?
0.992 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/community: Permission denied
seems like you are not allowed to access this uri? 

Maybe if you change from https to http this could solve your network problem or get in contact with your IT department 
https://gitlab.alpinelinux.org/alpine/aports/-/issues/15716

So in my opinion this is a docker/local network related problem. Its not connected to the SDK.
